### ISSUE TITLE
Zoom links get cut away when exiting and re-entering program

### ISSUE THREAD

**Issue by farice9** [AY2021S1-CS2113T-T12-1/tp#192]
For example I copied:

![image](https://user-images.githubusercontent.com/56571027/98118391-1e9f4d80-1ee6-11eb-9574-9fe0709f71f6.png)

Then when I exit and re-enter program the values after "=" are deleted

![image](https://user-images.githubusercontent.com/56571027/98118487-3e367600-1ee6-11eb-947f-4f44fee035ff.png)

**Comment by lingsihui** [comment]
Thanks!
