### ISSUE TITLE
Note: Run "gradlew build" to check for style before pushing

### ISSUE THREAD

**Issue by farice9** [AY2021S1-CS2113T-T12-1/tp#39]
It'll inform you if it fails so that you can fix the style before pushing.

To identify the individual errors:
1. Run "gradlew build" on intellij
2. Open build > reports > checkstyle > main.html
![image](https://user-images.githubusercontent.com/56571027/95671827-b5ba0380-0bcd-11eb-83c0-acc9ad665c9d.png)
3. Drag and drop the file to a web browser and you'll see this
![image](https://user-images.githubusercontent.com/56571027/95671833-c36f8900-0bcd-11eb-83d8-48d186b0f5c5.png)

**Comment by lingsihui** [comment]
Thanks for the reminder!
